### PR TITLE
Update _variables.scss

### PR DESCRIPTION
**Pull request by EmanueleGhelfi**
Update titles such that they do not scream to users

### CODE REVIEW

**Comment by EmanueleGhelfi** [comment]
@galeone any update on this?

**Comment by galeone** [comment]
You have to update this PR if you want it to be merged.

The big issue here is that while a smaller font looks OK in the homepage, it looks ugly when the post is kept singularly.
If you change the font size in the post list, but you keep the current font in the single article, I'm pretty sure I will accept your PR

**Comment by galeone** [comment]
@EmanueleGhelfi any update on this?

**Comment by galeone** [comment]
@EmanueleGhelfi updates? I'm going to close this issue the 16th September

**Comment by galeone** [comment]
In the end, I like it in this way.

**Pull request closed without merging**
